config/routes.rb
Rails.application.routes.draw do

  namespace :account do
    resources :groups
    resources :posts
    
    resources :blogs
    resources :comments
  end

  devise_for :users

  root "pages#index"

  get 'home' => "pages#index"

  resources :blogs do
    resources :comments
  end

  resources :groups do
    member do
      post :join
      post :quit
    end

    resources :posts
  end

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	validates :title, presence: true

	has_many :comments, dependent: :destroy

	belongs_to :owner, class_name: "User", foreign_key: :user_id

	def editable_by?(user)
	  user && user == owner
	end
end

app/controllers/account/blogs_controller.rb
class Account::BlogsController < ApplicationController
	before_action :authenticate_user!

	def index
  		@blogs = current_user.blogs.order("updated_at DESC")
	end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	before_action :authenticate_user!, only: [:edit, :update, :destroy]
	def index
		@blogs = Blog.all
	end

	def show
		@blog = Blog.find(params[:id])
		@comments = @blog.comments
	end

	def new
		@blog = current_user.blogs.new
	end
	 
	def edit
		@blog = current_user.blogs.find(params[:id])
	end

	def create
		@blog = current_user.blogs.new(blog_params)

		if @blog.save
		  redirect_to blogs_path
		else
		  render :new
		end
	end

	def update
		@blog = current_user.blogs.find(params[:id])

		if @blog.update(blog_params)
		  redirect_to blog_path, notice: "修改文章成功"
		else
		  render :edit
		end
	end

	def destroy
		@blog = current_user.blogs.find(params[:id])
		@blog.destroy
		redirect_to blogs_path, alert: "文章已刪除"
	end

	private
	
	def blog_params 
	  params.require(:blog).permit(:title, :categroies, :content)
	end

end

app/helpers/account/blogs_helper.rb
module Account::BlogsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_sidebar.html.erb
<!-- Blog Sidebar Widgets Column -->
<div class="col-md-4">

    <!-- Blog Search Well -->
    <div class="well">
        <h4>Blog Search</h4>
        <div class="input-group">
            <input type="text" class="form-control">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button">
                    <span class="glyphicon glyphicon-search"></span>
            </button>
            </span>
        </div>
        <!-- /.input-group -->
    </div>

    <!-- Blog Categories Well -->
    <div class="well">
        <h4>Blog Categories</h4>
        <div class="row">
            <div class="col-lg-6">
                <ul class="list-unstyled">
                    <li><a href="#">Category Name</a>
                    </li>
                    <li><a href="#">Category Name</a>
                    </li>
                    <li><a href="#">Category Name</a>
                    </li>
                    <li><a href="#">Category Name</a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-6">
                <ul class="list-unstyled">
                    <li><a href="#">Category Name</a>
                    </li>
                    <li><a href="#">Category Name</a>
                    </li>
                    <li><a href="#">Category Name</a>
                    </li>
                    <li><a href="#">Category Name</a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- /.row -->
    </div>

    <!-- Side Widget Well -->
    <div class="well">
        <h4>Side Widget Well</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
    </div>

</div>

app/views/blogs/edit.html.erb
<!-- Page Content -->
    <div class="container">

        <div class="row">
			<div class="col-md-8 col-md-offset-2">
			  <h1>修改文章</h1>

			  <hr>
			  <%= simple_form_for @blog do |f| %>
			    <div class="form-blog">
			      <%= f.input :title, input_html: { class: "form-control"} %>
			      <%= f.input :categroies, input_html: { class: "form-control"} %>
			      <%= f.input :content, input_html: { class: "form-control"} %>
			    </div>
			    <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting..." } %>
			  <% end %>
			</div>
		</div>
	</div>	

app/views/blogs/index.html.erb
<!-- Page Content -->
<%= render "common/bar" %>
    <div class="container">

        <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">

                <h1 class="page-header">
                    開發日誌
                    <small>我們到底做了什麼</small>
                </h1>
                <%= link_to("新增文章", new_blog_path, class: "btn btn-primary pull-right") %>
                <!-- Blog Post -->
                <% @blogs.each do |blog| %>
                <h2>
                    <a href="<%= blog_path(blog) %>"><%= blog.title %></a>
                </h2>
                <p class="lead">
                    by <a href="#"><%= blog.owner.name %></a>
                </p>
                <p><span class="glyphicon glyphicon-time"></span> <%= blog.created_at %> </p>
                <hr>
                <!-- <img class="img-responsive" src="http://placehold.it/900x300" alt=""> -->
                <!-- <hr> -->
                <p><%= blog.content %></p>
                <a class="btn btn-primary" href="<%= blog_path(blog) %>">繼續閱讀 <span class="glyphicon glyphicon-chevron-right"></span></a>

                <hr>
                <% end %>

                <!-- Pager -->
                <!-- <ul class="pager">
                    <li class="previous">
                        <a href="#">&larr; Older</a>
                    </li>
                    <li class="next">
                        <a href="#">Newer &rarr;</a>
                    </li>
                </ul> -->

            </div>

            <%= render 'sidebar' %>

        </div>
        <!-- /.row -->

app/views/blogs/new.html.erb
<!-- Page Content -->
    <div class="container">

        <div class="row">
			<div class="col-md-8 col-md-offset-2">
			  <h1>新增文章</h1>

			  <hr>
			  <%= simple_form_for @blog do |f| %>
			    <div class="form-blog">
			      <%= f.input :title, input_html: { class: "form-control"} %>
			      <%= f.input :categroies, input_html: { class: "form-control"} %>
			      <%= f.input :content, input_html: { class: "form-control"} %>
			    </div>
			    <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting..." } %>
			  <% end %>
			</div>
		</div>
	</div>	

app/views/blogs/show.html.erb
<!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">

                <!-- Blog Post -->

                <!-- Title -->
                <h1><%= @blog.title %></h1>
                
                <!-- Author -->
                <p class="lead">
                    by <a href="#"><%= @blog.owner.name %></a>
                </p>
                <% if @blog.editable_by?(current_user) %>
                    <%= link_to("編輯文章", edit_blog_path, class: "btn btn-primary") %>
                    <%= link_to("刪除文章", blog_path(@blog),class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?" } )%>
                <% end %>
                <hr>

                <!-- Date/Time -->
                <p><span class="glyphicon glyphicon-time"></span><%= @blog.created_at %></p>
                <hr>

                <!-- Preview Image -->
                <!-- <img class="img-responsive" src="http://placehold.it/900x300" alt=""> -->

                <!-- <hr> -->

                <!-- Post Content -->
                
                
                <p><%= @blog.content %></p>
                <hr>
                <!-- Comments Form -->
                <%= link_to("回應", new_blog_comment_path(@blog), class: "btn btn-info") %>
                <hr>
                <!-- Posted Comments -->

                
                <!-- Comment -->
                <% @comments.each do |comment| %>
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="http://placehold.it/64x64" alt="">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading"><%= comment.author.name %>
                            <small><%= comment.created_at %></small>
                        </h4>
                        <%= comment.content %>
                    </div>
                    <% if comment.editable_by?(current_user) %>
                        <%= link_to("編輯回應", edit_blog_comment_path(comment.blog, comment),
                            class: "btn btn-default btn-xs btn-warning")%>
                        <%= link_to("刪除回應", blog_comment_path(comment.blog, comment),
                            class: "btn btn-default btn-xs btn-danger ", method: :delete, 
                            data: { confirm: "確認刪除？" } )%>
                        <% end %>
                </div>
                <% end %>
            </div>

            <%= render 'sidebar' %>

        </div>
        <!-- /.row -->