config/routes.rb
Rails.application.routes.draw do

  namespace :account do
    resources :groups
    resources :posts
    
    resources :blogs
    resources :comments
  end

  devise_for :users

  root "pages#index"

  get 'home' => "pages#index"

  resources :blogs do
    resources :comments
  end

  resources :groups do
    member do
      post :join
      post :quit
    end

    resources :posts
  end

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	validates :title, presence: true

	has_many :comments, dependent: :destroy

	belongs_to :owner, class_name: "User", foreign_key: :user_id

	def editable_by?(user)
	  user && user == owner
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :blog, counter_cache: :posts_count
	validates :content, presence: true

	belongs_to :author, class_name: "User", foreign_key: :user_id

	def editable_by?(user)
	  user && user == author
	end
end

app/models/group.rb
class Group < ActiveRecord::Base
	# validates :title, presence: true
	validates :title, presence:{ message: "標題不可為空白" }

	has_many :posts, dependent: :destroy
	has_many :group_users
	has_many :members, through: :group_users, source: :user
	belongs_to :owner, class_name: "User", foreign_key: :user_id

	def editable_by?(user)
	  user && user == owner
	end
end

app/models/group_user.rb
class GroupUser < ActiveRecord::Base
	belongs_to :user
	belongs_to :group
end

app/models/post.rb
class Post < ActiveRecord::Base
	scope :recent, -> { order("updated_at DESC") }
	
	belongs_to :group, counter_cache: :posts_count
	validates :content, presence: true

	belongs_to :author, class_name: "User", foreign_key: :user_id
	def editable_by?(user)
	  user && user == author
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :groups
  has_many :posts

  has_many :blogs
  has_many :comments

  has_many :group_users
  has_many :participated_groups, through: :group_users, source: :group

  	def join!(group)
  		participated_groups << group
  	end

  	def quit!(group)
  		participated_groups.delete(group)
  	end

	def is_member_of?(group)
	  participated_groups.include?(group)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
  	devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	before_action :authenticate_user!, only: [:edit, :update, :destroy]
	def index
		@blogs = Blog.all
	end

	def show
		@blog = Blog.find(params[:id])
		@comments = @blog.comments
	end

	def new
		@blog = current_user.blogs.new
	end
	 
	def edit
		@blog = current_user.blogs.find(params[:id])
	end

	def create
		@blog = current_user.blogs.new(blog_params)

		if @blog.save
		  redirect_to blogs_path
		else
		  render :new
		end
	end

	def update
		@blog = current_user.blogs.find(params[:id])

		if @blog.update(blog_params)
		  redirect_to blog_path, notice: "修改文章成功"
		else
		  render :edit
		end
	end

	def destroy
		@blog = current_user.blogs.find(params[:id])
		@blog.destroy
		redirect_to blogs_path, alert: "文章已刪除"
	end

	private
	
	def blog_params 
	  params.require(:blog).permit(:title, :categroies, :content)
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_blog
	before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
	def new
		@comment = @blog.comments.new
	end
	
	def edit
		@comment = current_user.comments.find(params[:id])
	end
	
	def create
		@comment = @blog.comments.build(comment_params)
		@comment.author = current_user
	
	   if @comment.save
	     redirect_to blog_path(@blog), notice: "新增回應成功！"
	   else
	     render :new
	   end
	end
	
	def update
	   @comment = current_user.comments.find(params[:id])
	
	   if @comment.update(comment_params)
	     redirect_to blog_path(@blog), notice: "回應修改成功！"
	   else
	     render :edit
	   end
	end
	
	def destroy
	   @comment = current_user.comments.find(params[:id])
	
	   @comment.destroy
	   redirect_to blog_path(@blog), alert: "回應已刪除"
	end

	private	

	def comment_params
  	params.require(:comment).permit(:content)
	end

	def find_blog
      @blog = Blog.find(params[:blog_id])
  	end  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	before_action :authenticate_user!, only: ["new, :edit, :create, :update, :destory"]
	def index
		flash[:notice] = "Good morning!"
		@groups = Group.all
	end

	def show
		@group = Group.find(params[:id])
		@posts = @group.posts
	end

	def new
		@group = Group.new	
	end

	def edit
		@group = current_user.groups.find(params[:id])
	end

	def create
		@group = current_user.groups.new(group_params)
	
	   if @group.save
	   	current_user.join!(@group)
	    redirect_to groups_path
	   else
	     render :new
	   end
	end

 	def update
	   @group = current_user.groups.find(params[:id])
	
	   if @group.update(group_params)
	     redirect_to groups_path, notice: "修改討論版成功"
	   else
	     render :edit
	   end
	end

	def destroy
		@group = current_user.groups.find(params[:id])
		@group.destroy
		redirect_to groups_path, alert: "討論板已刪除"
	end

	def join
		@group = Group.find(params[:id])

		if !current_user.is_member_of?(@group)
			current_user.join!(@group)
			flash[:notice] = "成功加入本討論版"
		else
			flash[:notice] = "你已經是本討論板成員了"
		end

		redirect_to group_path(@group)
	end

	def quit
		@group = Group.find(params[:id])

		if current_user.is_member_of?(@group)
			current_user.quit!(@group)
			flash[:alert] = "成功退出本討論版"
		else
			flash[:warning] = "你並不是本討論板成員"
		end

		redirect_to group_path(@group)
	end

	private

	def group_params 
	  params.require(:group).permit(:title, :description)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_group
	before_action :authenticate_user!
	before_action :member_required, only: [:new, :create ]
	def new
		@post = @group.posts.new
	end
	
	def edit
		@post = current_user.posts.find(params[:id])
	end
	
	def create
		@post = @group.posts.build(post_params)
		@post.author = current_user
		if @post.save
			redirect_to group_path(@group), notice:"新增文章成功"
		else
			render :new
		end
	end
	
	def update
		@post = current_user.posts.find(params[:id])

		if @post.update(post_params)
			redirect_to group_path(@group), notice:"文章修改成功！"
		else
			render :edit
		end
	end
	
	def destroy
		@post = current_user.posts.find(params[:id])

		@post.destroy
		redirect_to group_path, alert:"文章刪除成功！"
	end

	private

	def post_params
		params.require(:post).permit(:content)
	end

	def find_group
		@group = Group.find(params[:group_id])
	end

	def member_required
	  if !current_user.is_member_of?(@group)
	    flash[:warning] = "你不是這個討論版的成員，不能發文喔！"
	    redirect_to group_path(@group)
	  end
	end
end

app/helpers/account/blogs_helper.rb
module Account::BlogsHelper
end

app/helpers/account/posts_helper.rb
module Account::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def notice_message
		alert_types = { notice: :success, alert: :danger }

		close_button_options = { class: "close", "data-dismiss" => "alert", "aria-hidden" => true }
		close_button = content_tag( :button, "x", close_button_options )

		alerts = flash.map do | type, message |
			alert_content = close_button + message

			alert_type = alert_types[type.to_sym] || type
			alert_class = "alert alert-#{alert_type} alert-dismissable"

			content_tag(:div, alert_content, class: alert_class)
		end

		alerts.join("\n").html_safe
	end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def render_post_content(post)
		truncate(post.content, length: 50)
	end	
end

app/views/common/_bar.html.erb
<%= stylesheet_link_tag 'demo' %>
	<%= javascript_include_tag 'jquery.min' %>

</head>

<script>
  $('#edit-search-block-form-1').click(
    function() {
      $(this).val("");
    }
  )
  </script>
  <script type="text/javascript">
function btn_query(tmpsts,tmpid){
	// var err_msg = '';
	// var frm = document.frmQuery;
	var frm = document.getElementById('q');
	
}
</script>
<link href="/assets/stylesheets/demo.css.erb" rel="stylesheet">
<script src="/assets/javascripts/jquery.min.js"></script>
<script type="text/javascript">
$(function(){

//滑鼠移致選項
$("#myMenu").children().on("mouseenter",function(){
 //alert(""+$(this).index());
 var idx=$(this).index();
	if(idx==0||idx==5||idx==8){
		if($(this).attr("class")=='c'+idx+' nav1'){
		    $(this).children().show();
			$(this).removeClass("c"+idx);
			$(this).removeClass("nav1").addClass("sel"+idx).show();				
		}
	}
 
});

//滑鼠離開選項
$("#myMenu").children().on("mouseleave",function(){
var idx=$(this).index();
	if(idx==0||idx==5||idx==8){	    
		if($(this).attr("class")=='sel'+idx){            	
			$(this).removeClass("sel"+idx).addClass("c"+idx).addClass("nav1");	
            $(this).children().hide();						
		}
	}
 
});
});
</script>
</td>

</tr>
  <body>
  <table width="1028" align="center">
    <td width="1" rowspan="7">&nbsp;</td>
    <td height="86"></td>
  <tr>
    <td height="480"  colspan="6">
    <div class=newMenu>
    <div class="myPic0"><%= image_tag("c0b.png") %></div>
    </div>
   <div id="myMenu" style="margin:0 auto;width:1010px;height:400px;background:url('<%= asset_path("bar.png") %>');position:relative;">
<div class="c0 nav1">
	<div style="display:none">
	<a  href="https://github.com/UscStudentProject/LOWMAP" class="Items" style="position:absolute;top:200px;left:140px;padding:0;width:80px;height:110px;"></a>
	
	</div>
</div>
<div class="nav1" style="display: none;"></div>
<div class="nav1" style="display: none;"></div>
<div class="nav1" style="display: none;"></div>
<div class="c4 nav1">
	<div style="display:block">
		
	</div>
</div>
<div class="c5 nav1">
	<div style="display:none">
		<a  href="http://lunch.dataworkplace.net/blogs" class="Items" style="position:absolute;top:230px;left:455px;padding:0;width:110px;height:80px"></a>
			
	</div>
</div>
<div class="nav1" style="display: none;"></div>
<div class="nav1" style="display: none;"></div>
<div class="c8 nav1">
	<div style="display:none">
		<a  href="http://lunch.dataworkplace.net/blogs" class="Items" style="position:absolute;top:230px;left:945px;padding:0;width:110px;height:80px"></a>
	</div>
</div>

<div class="nav1" style="display: none;"></div>
<div class="nav1" style="display: none;"></div>
</div>


</body>
</html>

app/views/common/_footer.html.erb
<!-- Footer -->

        <footer class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; 實踐大學學生社群 x 午餐計畫 2015</p>
                </div>
            </div>
        </footer>

app/views/common/_form.html.erb
<%= simple_form_for group do |f| %>
  <div class="form-group">
    <%= f.input :title, input_html: { class: "form-control"} %>
    <%= f.input :description, input_html: { class: "form-control"} %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting..." } %>
<% end %>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
     <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand page-scroll" href="/">午餐計畫</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to("開發日誌", blogs_path) %></li>
        <% if !current_user %>
        <li><%= link_to("註冊", new_user_registration_path) %></li>
        <li><%= link_to("登入", new_user_session_path) %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span>Hi! <%= current_user.name %></span>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to("編輯帳號資訊", edit_user_registration_path) %></li>
              <li><%= link_to("已發布文章", account_blogs_path) %></li>
              <li><%= link_to("已發布文章回應", account_comments_path) %></li>
              <li><%= link_to("登出", destroy_user_session_path, :method => :delete) %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="UscStudentProject">

	<title>Lunch Project</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

	<%= csrf_meta_tags %>
</head>
<body>
<%= render "common/navbar" %>
<%= notice_message %>
<%= yield %>
<%= render "common/footer" %>

</body>
</html>

app/views/pages/index.html.erb
<!-- Full Width Image Header -->
    <header class="header-image">
        <div class="headline">
            <div class="container">
                <h1>又到了吃飯時間了</h1>
                <h2>多拉O夢，到底該吃什麼好呢？</h2>
            </div>
        </div>
    </header>

    <!-- Page Content -->
    <div class="container">

        <hr class="featurette-divider">

        <!-- First Featurette -->
        <div class="featurette" id="about">
            <%= image_tag("portfolio/2.jpg", class: "featurette-image img-circle img-responsive pull-right") %>
            <h2 class="featurette-heading">This First Heading
                <span class="text-muted">Will Catch Your Eye</span>
            </h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>

        <hr class="featurette-divider">

        <!-- Second Featurette -->
        <div class="featurette" id="services">
            <%= image_tag("portfolio/3.jpg", class: "featurette-image img-circle img-responsive pull-left") %>
            <h2 class="featurette-heading">The Second Heading
                <span class="text-muted">Is Pretty Cool Too.</span>
            </h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>

        <hr class="featurette-divider">

        <!-- Third Featurette -->
        <div class="featurette" id="contact">
            <%= image_tag("portfolio/4.jpg", class: "featurette-image img-circle img-responsive pull-right") %>
            <h2 class="featurette-heading">The Third Heading
                <span class="text-muted">Will Seal the Deal.</span>
            </h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>

        <hr class="featurette-divider">

        

    </div>
    <!-- /.container -->